---
version: '3'
services:
  test: 
    image: picklewicklewickle/mm-dev
    container_name: mm-test
    ports: 
      - "3000:3000"
    volumes:
      - .:/user/src/app
      - node_modules:/user/src/app/node_modules
    command: npm run test
    depends_on: 
      - postgres-db-test
  postgres-db-test: 
    image: picklewicklewickle/mm-postgres
    container_name: mm-test-db
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=mmadmin
      - POSTGRES_DB=mmdb
    volumes:
      - test-db-volume:/var/lib/postgresql/data
volumes:
  node_modules: {}
  test-db-volume: {}